name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Snapcraft (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          SNAPCRAFT_VERSION=7.3.3
          curl -L https://github.com/snapcore/snapcraft/releases/download/$SNAPCRAFT_VERSION/snapcraft-$SNAPCRAFT_VERSION-linux-amd64.tar.gz -o snapcraft.tar.gz
          sudo tar -xzf snapcraft.tar.gz -C /usr/local/bin --strip-components=1
          snapcraft --version

      - name: Build App
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            npm run build:linux
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            npm run build:win
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            npm run build:mac
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Generate Release Notes
        run: |
          echo "# SpreadCombine ${GITHUB_REF_NAME}" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## What's New" >> RELEASE_NOTES.md
          echo "- Linux: AppImage, Snap, DEB, RPM" >> RELEASE_NOTES.md
          echo "- Windows: EXE" >> RELEASE_NOTES.md
          echo "- macOS: DMG" >> RELEASE_NOTES.md
          echo "- ## ***It Is The First Release**" >> RELEASE_NOTES.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body_path: RELEASE_NOTES.md
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}